### ISSUE TITLE
Getting tasks from any.do account and rendering them

### ISSUE THREAD

**Issue by RoseGoldHeart** [davoam/anydo-api#10]
Hi!

I'm not really experienced with any api whatsoever so I'm still discovering a bit but basically I wanted to display a list of tasks onn my to do list on a page I made. I tried doing this 

>  const myTasks = api.sync();
> const app = document.getElementById('app');
 
Annd then  I tried to loop through myTasks and just listing the differennt elements. This did not work though, am I wrong thinking api.sync() returns an array? If it returns an object what would be the key-value pairs be? 

thanks in advance for your response!

**Comment by davoam** [comment]
Hi @RoseGoldHeart ! 

Actually the `api.sync()` call returns a `Promise`, and in its `then` callback function `promise.then((tasks) => {...do something here})` you can read the tasks.

Please check the [example](https://github.com/davoam/anydo-api#example) in the `README.md`

**Comment by RoseGoldHeart** [comment]
Oh I think I'm starting to get it. I'm very bad at async javascript but I'll try some stuff out and try to get it. Just to get a hint what should I write in the brackets if I were to return the title of a task?

thanks a lot for your help :)

**Comment by davoam** [comment]
> @davoam Oh I think I'm starting to get it. I'm very bad at async javascript but I'll try some stuff out and try to get it. Just to get a hint what should I write in the brackets if I were to return the title of a task?
> 
> thanks a lot for your help :)

Please check the example file mentioned earlier. It will make things more clear
