### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by RoseGoldHeart** [davoam/anydo-api#11]
Hello! 
I'm trying to integrate my anydo list in my web app using this code (just to test if I can actually access the data): 
`api.sync()
	.then((tasks) => {
		console.log(tasks);
	})
	.catch((error) => {
		console.log(error);
	});`

But I get a POST 401 error... This is what the headers say:

POST
	https://sm-prod2.any.do/login
Status401
Unauthorized
VersionHTTP/2
Transferred917 B (34 B size)
Referrer Policyno-referrer-when-downgrade

Response Header:
    Accept
    	application/json
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Content-Length
    	55
    content-type
    	application/json
    Host
    	sm-prod2.any.do
    Origin
    	http://localhost:3000
    Referer
    	http://localhost:3000/
    User-Agent
    	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:85.0) Gecko/20100101 Firefox/85.0

**Comment by davoam** [comment]
Hi @RoseGoldHeart ! 

Please make sure that your login and password are correct. 401 error usually means that user passed wrong credentials
